services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source code for hot reload
      - .:/app
      # Prevent node_modules from being overridden
      - /app/node_modules
      - /app/.next
    networks:
      - sales-network
    restart: unless-stopped

networks:
  sales-network:
    external: true